In [6]:
from collections import deque
import numpy as np

# Fungsi untuk mengubah posisi puzzle menjadi string untuk memudahkan perbandingan
def puzzle_to_string(puzzle):
    return ''.join(str(i) for i in puzzle)

# Fungsi untuk mendapatkan posisi kosong (0)
def find_empty(puzzle):
    return puzzle.index(0)

# Fungsi untuk memindahkan posisi puzzle
def move_puzzle(puzzle, empty_pos, new_pos):
    puzzle_list = list(puzzle)
    puzzle_list[empty_pos], puzzle_list[new_pos] = puzzle_list[new_pos], puzzle_list[empty_pos]
    return tuple(puzzle_list)

# Fungsi untuk BFS
def bfs(start, goal):
    queue = deque([(start, [])])  # Menyimpan puzzle dan langkah-langkah yang diambil
    visited = set([start])

    # Gerakan yang mungkin: kiri, kanan, atas, bawah
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]  # Baris, Kolom

    while queue:
        current_state, path = queue.popleft()

        if current_state == goal:
            return path

        empty_pos = find_empty(current_state)
        empty_row, empty_col = divmod(empty_pos, 3)  # Menentukan baris dan kolom dari posisi kosong

        # Coba semua gerakan
        for dr, dc in moves:
            new_row, new_col = empty_row + dr, empty_col + dc
            if 0 <= new_row < 3 and 0 <= new_col < 3:
                new_pos = new_row * 3 + new_col
                new_state = move_puzzle(current_state, empty_pos, new_pos)
                if new_state not in visited:
                    visited.add(new_state)
                    queue.append((new_state, path + [new_state]))

    return None  # Tidak ada solusi ditemukan

# Fungsi untuk menampilkan langkah-langkah solusi
def print_solution(path):
    for state in path:
        print(np.array(state).reshape(3, 3))
        print()

# Representasi puzzle awal dan tujuan
start_state = (1, 3, 2, 8, 5, 6, 7, 4, 0)  # Urutan awal
goal_state = (1, 2, 3, 4, 5, 6, 7, 8, 0)  # Urutan tujuan

# Menerapkan BFS untuk mencari solusi
path = bfs(start_state, goal_state)

if path:
    print("Langkah-langkah menuju solusi:")
    print_solution(path)
else:
    print("Tidak ada solusi ditemukan.")


Langkah-langkah menuju solusi:
[[1 3 2]
 [8 5 0]
 [7 4 6]]

[[1 3 2]
 [8 0 5]
 [7 4 6]]

[[1 0 2]
 [8 3 5]
 [7 4 6]]

[[0 1 2]
 [8 3 5]
 [7 4 6]]

[[8 1 2]
 [0 3 5]
 [7 4 6]]

[[8 1 2]
 [7 3 5]
 [0 4 6]]

[[8 1 2]
 [7 3 5]
 [4 0 6]]

[[8 1 2]
 [7 3 5]
 [4 6 0]]

[[8 1 2]
 [7 3 0]
 [4 6 5]]

[[8 1 2]
 [7 0 3]
 [4 6 5]]

[[8 1 2]
 [0 7 3]
 [4 6 5]]

[[0 1 2]
 [8 7 3]
 [4 6 5]]

[[1 0 2]
 [8 7 3]
 [4 6 5]]

[[1 2 0]
 [8 7 3]
 [4 6 5]]

[[1 2 3]
 [8 7 0]
 [4 6 5]]

[[1 2 3]
 [8 7 5]
 [4 6 0]]

[[1 2 3]
 [8 7 5]
 [4 0 6]]

[[1 2 3]
 [8 0 5]
 [4 7 6]]

[[1 2 3]
 [0 8 5]
 [4 7 6]]

[[1 2 3]
 [4 8 5]
 [0 7 6]]

[[1 2 3]
 [4 8 5]
 [7 0 6]]

[[1 2 3]
 [4 0 5]
 [7 8 6]]

[[1 2 3]
 [4 5 0]
 [7 8 6]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]

